apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: my-nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      livenessProbe: # Any code greater than or equal to 200 and less than 400 indicates success
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 15
        timeoutSeconds: 2 # default: 1
        periodSeconds: 5 # default: 10
        failureThreshold: 1 # default: 3
      readinessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 5 # default: 10
        failureThreshold: 1 # default: 3
      startupProbe:
        httpGet:
          path: /index.html
          port: 80
        failureThreshold: 30
        periodSeconds: 10
# k create -f nginx.pod.yml --dry-run # --validate=true
# k create -f nginx.pod.yml --save-config
# k describe pod my-nginx
# k apply -f nginx.pod.yml
# k exec my-nginx -it sh
# k edit -f nginx.pod.yml
# k delete -f nginx.pod.yml
