apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: my-nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
          hostPort: 8080

# k create -f nginx.pod.yml --dry-run # --validate=true
# k create -f nginx.pod.yml --save-config
# k describe pod my-nginx
# k apply -f nginx.pod.yml
# k exec my-nginx -it sh
# k edit -f nginx.pod.yml
# k delete -f nginx.pod.yml